global:
  scrape_interval:     5s
  evaluation_interval: 5s

rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: produtos-rest-grpc-app
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:5002']
        labels:
          group: 'fbiopereira'