version: '3.1'

services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pwd
    volumes:
      - ../dados-mongo:/data/db
    networks:
      - "fbiopereira"

  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: pwd
      ME_CONFIG_MONGODB_URL: mongodb://user:pwd@mongo:27017/
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - "fbiopereira"



networks:
  fbiopereira:
    driver: bridge
