version: '3.1'

services:
  postgres:
    image: postgres:14.4
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
      - ../dados-postgres:/var/lib/postgresql/data
    networks:
      - "fbiopereira"

  pgadmin:
    image: dpage/pgadmin4:6.11
    container_name: pgadmin
    restart: always
    ports:
      - 7001:80
    environment:
      PGADMIN_DEFAULT_EMAIL: fabio.pereira@outlook.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - "fbiopereira"

networks:
  fbiopereira:
    driver: bridge